<%@ Page Title="" Language="C#" MasterPageFile="~/NOTWWWROOT/MasterPage.master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="container">
        <h1 class="text-primary">James Hetfield</h1>
        <hr />
            <div class="row">
                <div class="col-md-8">James Alan Hetfield (born August 3, 1963) is an American musician, singer, and songwriter known for being the co-founder, lead vocalist, rhythm guitarist, and main songwriter for the American heavy metal band Metallica. Hetfield is mainly known for his intricate rhythm playing, but occasionally performs lead guitar duties and solos, both live and in the studio. Hetfield co-founded Metallica in October 1981 after answering a classified advertisement by drummer Lars Ulrich in the Los Angeles newspaper The Recycler. Metallica has won nine Grammy Awards and released ten studio albums, three live albums, four extended plays and 24 singles.In 2009, Hetfield was ranked at no. 8 in Joel McIver's book The 100 Greatest Metal Guitarists,[1] and ranked at no. 24 by Hit Parader on their list of the 100 Greatest Metal Vocalists of All Time. In Guitar World's poll, Hetfield was placed as the 19th greatest guitarist of all time, as well as being placed second (along with Metallica lead guitarist Kirk Hammett) in The 100 Greatest Metal Guitarists poll of the same magazine. Rolling Stone placed Hetfield as the 87th greatest guitarist of all time.</div>
                <div class="col-md-4"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/JamesHetfield2012.jpg/250px-JamesHetfield2012.jpg" /></div>
            </div>
            <h3 class="text-info">Career</h3>
            <hr />
            <p>
                In the early days of the band, Metallica experimented with a few different vocals and guitar combinations, essentially creating a setup similar to that of British metal band Diamond Head, another major influence on Hetfield. Some of the options considered included adding another guitar player, having John Roads play lead guitar, as well as asking John Bush from Armored Saint (who later joined Anthrax) to sing for the band. The finalized line-up of the band became Hetfield (lead vocals and rhythm guitar), Lars Ulrich (drums), Dave Mustaine (lead guitar), and Ron McGovney (bass) who was soon replaced by Cliff Burton. Hetfield referred to their early sound as power metal. The term "thrash metal" was first used when Kerrang journalist Malcolm Dome described the Anthrax song "Metal Thrashing Mad" in an issue of Kerrang in February 1984.[8]
                From 1982 to 1983, Mustaine's alcoholism sparked heated altercations between himself and Hetfield.[9] Mustaine also once poured beer onto McGovney's bass[9] nearly causing serious damage. On April 1, 1983, the band recruited lead guitarist Kirk Hammett from the band Exodus and 10 days later Hetfield and Ulrich officially removed Mustaine from the band due to his alcoholic tendencies.[9][10] Mustaine was sent home on a 4-day bus journey, and went on to form the heavy metal band Megadeth.
                Until the mid-1990s, Hetfield recorded all rhythm tracks and most harmony tracks.[citation needed] Since the recording of Load, Hammett has been recording rhythm guitars as well. Hetfield occasionally plays guitar solos on songs such as "Nothing Else Matters", "My Friend of Misery", "Just a Bullet Away", the outro solo on "The Outlaw Torn", the second solo on "To Live Is to Die", the first solo on "Suicide and Redemption", the first interlude solo on "Master of Puppets", the harmonized solo on "Orion" and the introduction for "The Day That Never Comes". He also writes the majority of the guitar harmonies, as well as writing the lyrics, vocal melodies, and co-arranging the songs with Ulrich. Hetfield has been involved in a number of onstage accidents, most notable being an incident with pyrotechnics at Olympic Stadium in Montreal during the Guns N' Roses/Metallica Stadium Tour on August 8, 1992. Hetfield was the victim of a severe pyrotechnics accident during the song "Fade to Black", in which a pyrotechnic charge exploded. Hetfield's guitar protected him from the full force of the blast; however, the fire engulfed his left side, burning his hand, arm, eyebrows, face and hair. He suffered second and third-degree burns, but was back on stage 17 days later, although his guitar duties were delegated to former guitar tech and Metal Church guitarist John Marshall for four weeks while he made a full recovery.[11]
                Hetfield has also broken his arm a number of times while skateboarding, which prevented him from playing guitar on stage, and subsequently caused Hetfield's management company Q Prime to add a clause in Hetfield's contract forbidding him to ride a skateboard while Metallica was touring.[12] During a live performance on tour for Metallica, Hetfield experienced complications with his vocals after performing a cover of the Anti-Nowhere League song "So What?", forcing him to take vocal lessons for the first time. He did basic warm-up exercises to piano keys with his vocal coach who also gave him a cassette tape of the piano warm-up for future use. Hetfield still uses the same cassette he was given in the early nineties to this day before any live performance or any recording Metallica does. Hetfield talks about his vocal training endeavors in the Metallica documentary film, Some Kind of Monster produced and directed by Joe Berlinger and Bruce Sinofsky.[13]
                During the recording of the band's eighth studio album St. Anger in 2001, Hetfield went into rehab to address his alcohol addiction. He rejoined the band after seven months in rehab and four months recovering with his family. He is now clean and sober and is determined to remain so, all of which is featured in Some Kind of Monster.[13] Some Kind of Monster also shows the making of the St. Anger album and documents the various conflicts and issues the band were facing at the time including the departure of Jason Newsted, alcoholism, family commitments, and the future of the band with many in the rock press questioning whether the band would even still be together to see the completion of the St. Anger album.
                Hetfield and Metallica addressed their need for a new bassist by recruiting Robert Trujillo, former bass player of Ozzy Osbourne. It was more of a swap since Ozzy Osbourne surprisingly recruited Jason Newsted shortly after Trujillo's transfer. The new line-up has continued to make music and tour worldwide. Metallica's ninth studio album, Death Magnetic, was released on September 12, 2008. Like St. Anger and every album of original material released by Metallica since 1991's Metallica, Death Magnetic went to #1 on the Billboard charts in over 30 countries during its first week of release.[14]
                On April 4, 2009, Hetfield, along with remaining Metallica members Ulrich, Hammett, Trujillo, as well as former bassist Newsted and the deceased Cliff Burton (who was represented by his father) were inducted into the Rock and Roll Hall of Fame.[15] In an interview after their nomination, Hetfield commented that everyone who had appeared on an album with the band would be inducted. This excluded original guitarist Dave Mustaine and original bassist Ron McGovney, as both had appeared only on the band's early demo tapes. Hetfield and the rest of Metallica, including Newsted, performed "Master of Puppets" and "Enter Sandman" to end the ceremony.
            </p>
    </div>
</asp:Content>

